---
language: go
sudo: false
notifications:
  email: joaosoft@gmail.com
jobs:
  include:
    - stage: test
      install:
        - go get github.com/joaosoft/dependency
        - dependency get
      os: linux
      go: master
      script:
        - go build ./elastic/joaosoft/
        - go build ./elastic/olivere/
        - go test ./elastic/joaosoft/
        - go test ./elastic/olivere/
        - go test -coverprofile=coverage.txt -covermode=atomic ./elastic/joaosoft/
        - go test -coverprofile=coverage.txt -covermode=atomic ./elastic/olivere/
        - go test ./elastic/joaosoft/ -bench=. -cpu=1,2,4,8
        - go test ./elastic/olivere/ -bench=. -cpu=1,2,4,8
        - go build ./logger/joaosoft/
        - go build ./logger/vredens/
        - go test ./logger/joaosoft/
        - go test ./logger/vredens/
        - go test -coverprofile=coverage.txt -covermode=atomic ./logger/joaosoft/
        - go test -coverprofile=coverage.txt -covermode=atomic ./logger/vredens/
        - go test ./logger/joaosoft/ -bench=. -cpu=1,2,4,8
        - go test ./logger/vredens/ -bench=. -cpu=1,2,4,8


      after_success:
        - bash <(curl -s https://codecov.io/bash)